# Generated by Django 4.1.3 on 2022-12-02 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight', '0007_flight_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lastname1', models.CharField(max_length=30)),
                ('lastname2', models.CharField(max_length=30)),
                ('cc', models.CharField(max_length=20)),
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='flight.flight')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
