# Generated by Django 4.1.3 on 2022-12-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='paid',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
