# Generated by Django 4.1.3 on 2022-12-04 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0009_flight_quantity'),
        ('ticket', '0003_ticket_created_alter_ticket_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flight.flight'),
        ),
    ]
