# Generated by Django 4.1.3 on 2022-12-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
