# Generated by Django 4.1.3 on 2022-12-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_flight_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='connections',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='flight',
            name='destination',
        ),
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.ManyToManyField(to='flight.city'),
        ),
    ]
