# Generated by Django 4.1.3 on 2022-12-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_city_flight_connections_alter_flight_creation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='destination',
            new_name='destinations',
        ),
    ]
