# Generated by Django 4.1.3 on 2022-12-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_rename_destination_flight_destinations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='destinations',
        ),
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='number_of_connections',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='flight',
            name='connections',
        ),
        migrations.AddField(
            model_name='flight',
            name='connections',
            field=models.ManyToManyField(to='flight.city'),
        ),
    ]
