# Generated by Django 4.1.3 on 2022-12-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_remove_flight_destinations_flight_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='connections',
            field=models.ManyToManyField(blank=True, null=True, to='flight.city'),
        ),
    ]
