# Generated by Django 4.1.3 on 2022-12-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0007_flight_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='number_of_connections',
            field=models.IntegerField(default=0),
        ),
    ]
