# Generated by Django 4.1.3 on 2022-12-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0008_alter_flight_number_of_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
